version: '3'

services:
  proxy:
    build: ./proxy_service
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - post_service

  user_service:
    build: ./user_service
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/mydatabase
      - POSTGRES_PASSWORD=password
    depends_on:
      postgres:
        condition: service_healthy

  post_service:
    build: ./post_service
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/mydatabase
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
