openapi: 3.0.0
info:
  title: User Service API
  version: 1.0.0

paths:
  /register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        200:
          description: User created successfully

  /login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Authentication successful

components:
  schemas:
    UserCreate:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        birth_date:
          type: string
          format: date
        phone:
          type: string
      required:
        - login
        - password
        - email

    LoginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
      required:
        - login
        - password

